### ISSUE TITLE
Compiling Test Suit Breaks

### ISSUE THREAD

**Issue by hamzazafar** [mpjexpress-project/mpjexpress#2]
Compiling MPJ Express test suit fails. Attachment contains logs of ant command.

[antLogs.txt](https://github.com/mpjexpress-project/mpjexpress/files/215011/antLogs.txt)

**Comment by thehappybug** [comment]
Seems like some helper classes were shifted without correcting the
namespaces. @noor-zehra saw this issue when running the benchmarks for NBC.
Will push the fixes on `master` branch soon. :)

**Comment by thehappybug** [comment]
@hex-dump Does that fix it?

**Comment by thehappybug** [comment]
Fixed. :smile:
